from django.urls import path

from .views import (
    LessonListCreateView,
    LessonRetrieveUpdateDestroyView,
    LessonTopicListCreateView,
    add_extra_lesson_view,
    admin_assign_makeup_view,
    approve_makeup_view,
    admin_makeups_view,
    conduct_lesson_view,
    create_makeup_request_view,
    makeup_invite_accept_view,
    makeup_invite_details_view,
    mark_attendance_view,
    my_attendance_view,
    reject_makeup_view,
    teacher_salary_view,
    my_makeups_view,
    parent_makeups_view,
    setup_group_schedule_view,
    suggest_makeup_slots_view,
    teacher_makeup_slots_view,
    update_makeup_slots_view,
)

urlpatterns = [
    path("topics/", LessonTopicListCreateView.as_view(), name="topics-list-create"),
    path("lessons/", LessonListCreateView.as_view(), name="lessons-list-create"),
    path("lessons/setup-group-schedule/", setup_group_schedule_view, name="lessons-setup-group-schedule"),
    path("lessons/add-extra/", add_extra_lesson_view, name="lessons-add-extra"),
    path("lessons/<int:pk>/", LessonRetrieveUpdateDestroyView.as_view(), name="lessons-detail"),
    path("lessons/<int:lesson_id>/conduct/", conduct_lesson_view, name="lessons-conduct"),
    path("lessons/makeup-slots/", update_makeup_slots_view, name="lessons-makeup-slots"),
    path("attendance/mark/", mark_attendance_view, name="attendance-mark"),
    path("attendance/my/", my_attendance_view, name="attendance-my"),
    path("teacher/salary/", teacher_salary_view, name="teacher-salary"),
    path("makeups/request/", create_makeup_request_view, name="makeups-request"),
    path("makeups/suggest/", suggest_makeup_slots_view, name="makeups-suggest"),
    path("makeups/my/", my_makeups_view, name="makeups-my"),
    path("makeups/parent/", parent_makeups_view, name="makeups-parent"),
    path("makeups/admin/", admin_makeups_view, name="makeups-admin"),
    path("makeups/<int:request_id>/approve/", approve_makeup_view, name="makeups-approve"),
    path("makeups/<int:request_id>/reject/", reject_makeup_view, name="makeups-reject"),
    path("makeups/admin/assign/", admin_assign_makeup_view, name="makeups-admin-assign"),
    path("makeups/invites/<str:token>/", makeup_invite_details_view, name="makeups-invite-details"),
    path("makeups/invites/<str:token>/accept/", makeup_invite_accept_view, name="makeups-invite-accept"),
    path("teacher/makeup-slots/", teacher_makeup_slots_view, name="teacher-makeup-slots"),
]
