# Generated by Django 4.2.11 on 2026-05-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_lesson_is_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='teacher_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='homework',
            field=models.TextField(blank=True),
        ),
    ]
