# Generated by Django 4.2.11 on 2026-05-09 09:43

import apps.attendance.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendancerecord_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeUpInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=apps.attendance.models._generate_invite_token, max_length=64, unique=True)),
                ('sent_to_email', models.EmailField(blank=True, max_length=254)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('absence_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makeup_invites', to='attendance.attendancerecord')),
                ('created_makeup_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites', to='attendance.makeuprequest')),
                ('makeup_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makeup_invites', to='attendance.lesson')),
            ],
            options={
                'indexes': [models.Index(fields=['token'], name='attendance__token_f0a9e3_idx')],
            },
        ),
    ]
