# Generated by Django 4.2.11 on 2026-05-09 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_location'),
        ('attendance', '0006_makeupinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='courses.location'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='makeup_capacity',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
