# Generated by Django 4.2.11 on 2026-05-09 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_seed_locations'),
        ('attendance', '0007_lesson_location_lesson_makeup_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.group'),
        ),
    ]
