server {
    listen 80;
    server_name _;
    client_max_body_size 25m;

    root /usr/share/nginx/html;
    index index.html;

    # API → Django (gunicorn)
    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Django admin (панель Django, не путать с /admin/ React)
    location /django-admin/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Portfolio PDF
    location /portfolio/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Раздача media и static напрямую через nginx
    location /media/ {
        alias /usr/share/nginx/media/;
        access_log off;
        expires 7d;
    }

    location /static/ {
        alias /usr/share/nginx/static/;
        access_log off;
        expires 30d;
    }

    # SPA fallback
    location / {
        try_files $uri $uri/ /index.html;
    }
}
