services:
  db:
    image: postgres:14
    container_name: kiberone_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: kiberone_backend
    env_file:
      - .env
    volumes:
      - ./backend:/app
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./frontend
    container_name: kiberone_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    ports:
      - "5173:5173"
    command: npm run dev -- --host 0.0.0.0 --port 5173

volumes:
  postgres_data:
