# Generated by Django 4.2.11 on 2026-05-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('absence', 'Пропуск'), ('makeup_approved', 'Подтверждение отработки'), ('payment_reminder', 'Напоминание о платеже')], max_length=32, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('body', models.TextField(help_text='Шаблон сообщения. Поддерживаются плейсхолдеры в стиле Python-format, например {student_name}, {lesson_topic}, {lesson_starts_at}, {remaining_lessons}.')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
