from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from .views import (
    admin_delete_project_view,
    admin_reset_user_password_view,
    change_password_view,
    churn_risk_view,
    create_user_view,
    dashboard_export_csv_view,
    dashboard_metrics_view,
    logout_view,
    parent_attendance_view,
    parent_billing_view,
    parent_children_view,
    password_reset_confirm_view,
    password_reset_request_view,
    profile_view,
    project_like_view,
    projects_feed_view,
    session_login_view,
    student_portfolio_pdf_view,
    student_portfolio_view,
    student_projects_view,
    teacher_student_detail_view,
    update_user_view,
)

urlpatterns = [
    path("session-login/", session_login_view, name="session-login"),
    path("logout/", logout_view, name="logout"),
    path("profile/", profile_view, name="profile"),
    path("password/reset-request/", password_reset_request_view, name="password-reset-request"),
    path("password/reset-confirm/", password_reset_confirm_view, name="password-reset-confirm"),
    path("password/change/", change_password_view, name="password-change"),
    path("users/", create_user_view, name="create-user"),
    path("users/<int:user_id>/", update_user_view, name="update-user"),
    path("users/<int:user_id>/reset-password/", admin_reset_user_password_view, name="admin-reset-user-password"),
    path("users/churn-risk/", churn_risk_view, name="users-churn-risk"),
    path("dashboard/metrics/", dashboard_metrics_view, name="dashboard-metrics"),
    path("dashboard/export.csv", dashboard_export_csv_view, name="dashboard-export-csv"),
    path("parent/children/", parent_children_view, name="parent-children"),
    path("parent/attendance/", parent_attendance_view, name="parent-attendance"),
    path("parent/billing/", parent_billing_view, name="parent-billing"),
    path("student/projects/", student_projects_view, name="student-projects"),
    path("student/portfolio/", student_portfolio_view, name="student-portfolio"),
    path("student/portfolio/pdf/", student_portfolio_pdf_view, name="student-portfolio-pdf"),
    path("teacher/students/<int:student_id>/", teacher_student_detail_view, name="teacher-student-detail"),
    path("projects/feed/", projects_feed_view, name="projects-feed"),
    path("projects/<int:project_id>/like/", project_like_view, name="projects-like"),
    path("projects/<int:project_id>/", admin_delete_project_view, name="admin-delete-project"),
    path("token/", TokenObtainPairView.as_view(), name="token-obtain-pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token-refresh"),
]
