# Generated by Django 4.2.11 on 2026-05-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_group_course_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcomment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
